### ISSUE TITLE
Irritating overview when changing home time zone

### ISSUE THREAD

**Issue by michikommader** [mathisdt/trackworktime#146]
### Boundary case
The working time overview table shows wrong IN/OUT entries when changing the home time zone.

### Reproduction
- Set home time zone to Germany (currently **GMT+1**)
- Add a "start tracking" event for 10:00 (10:01 a.m.)
- Add a "stop tracking" event for 22:01 (10:01 p.m.)
- The calculated worked time is correct with 12:01 h for this day.
- Now change home time zone to Uganda (**GMT+3**), for example.
- Chaos: Now in the overview table _for this day_ the IN time is rendered 10:00 but the OUT time is rendered 23:59 and additionally _the following day_ shows an OUT entry for 22:01 which is just wrong. Then summed working time is still correct with 12:01 h.

This interleaving breaks many calculations in my overview table when I have multiple events scattered throughout the day. Then also the summed working hours get totally wrong. I had the home time zone erroneously set to Uganda even though I am in Germany and spent quite a lot of time figuring out what was happening.

What is the point in setting the time zone anyway? If I add "start tracking" and "stop tracking" events in absolute, local time of where I am residing right now, why would I have to deal with a time zone other then my system's one?

**Comment by mathisdt** [comment]
I also can reproduce the problem, but I think changing the home time zone is not done frequently so this might only affect few users.

@dliw Did you intend the home time zone for users changing time zones physically (with their device) always having their data displayed in their home time? If you have some time, it would be nice if you could take a look. :blush:

**Comment by dliw** [comment]
That is intentional. Let me explain:
Originally, the app only stored the local time. This meant that the time calculation was incorrect during DST time changes. And, more importantly, when times came from different time zones. This is not particularly relevant for Central Europe, but in the rest of the world it can easily happen that you cross time zone boundaries several times a day. This was the main motivation for me to change the database to store timestamps, so that the calculation is correct in every case.
In my experience, however, one remembers local time. So if I want to check what time I checked out last week, for example, it would be very irritating to see the converted values there. It would be as if all values were always displayed in standard time, even if it is summer. That is why the database also saves the time zone offset, so that the local time is retained.
For the weekly table with individual days, however, one has to use a single time zone. From a bookkeeping point of view, it seems to me that only the home time zone makes sense here.

This leads to the current solution:
The overview and the calculation are always in the home time zone, the individual entries show the respective local time. This may be confusing at first glance, but in my opinion it is the most intuitive solution. I agree, however, that the entry "23:59" at the end of the day is actually wrong and should be changed. I got so used to it, that I didn't notice.

It would be possible to highlight times from different time zones somehow or add time zone information. But if you switch between time zones frequently, it is rather confusing and not really relevant information. Alternatively, a new option could be implemented to always show all times in the home time zone. This should be a relatively simple task.

@michikommader If it is just a few events - events can be edited and also the time zone can be changed.

**Comment by michikommader** [comment]
Thanks for the detailed explanation! I fixed my problems already and was just curious about how the time zone use cases were designed initially. It would indeed be nice to at least highlight to the user "that something is happening with the calculations regarding different time zones" :-)

**Comment by mathisdt** [comment]
@michikommader As your problem is solved, I close this issue. If you feel that there's anything left to do, please open a separate issue for that. Thanks!
