### ISSUE TITLE
Selecting a task with Llama

### ISSUE THREAD

**Issue by iceaway** [mathisdt/trackworktime#170]
I have just starting experimenting with Llama to automate clocking in (to get support for multiple SSIDs), but I cannot figure out how to clock in for a specific task. It's probably just the syntax in Llama that is causing issues, do you know exactly how it should look? Should it be the task ID or Task name? I have tried to set Extras in Llama to:
="task=_id_" and
="task=_Taskname_"

But neither seems to work.

**Comment by mathisdt** [comment]
I updated the screenshots and description on https://zephyrsoft.org/trackworktime to apply to the latest version of LlamaLab Automate. 
- You have to create broadcast intents with the action _org.zephyrsoft.trackworktime.ClockIn_ or _org.zephyrsoft.trackworktime.ClockOut_. 
- When using ClockIn, you can also set the parameters _task=..._ and _text=..._ in the "extra" section of the intent.

Here's how it can be done in Automate:

1. add a "Broadcast send" block:
![automate-1](https://user-images.githubusercontent.com/1932462/119236798-acb4eb80-bb39-11eb-9233-3855c6bb6fc7.png)
2. set the input arguments (observe the JSON object in "Extras" - you can use the task name with double quotes like in the example or the task ID without double quotes):
![automate-2](https://user-images.githubusercontent.com/1932462/119236807-b50d2680-bb39-11eb-8b18-be1183b87ba6.png)

If the issue is settled for you, please close this issue - or ask any follow-up questions that may arise. :smiley:

**Comment by iceaway** [comment]
Thanks a lot! Great service as always :-) I was missing out on the json-formatting part. I will try this asap and let you know. FYI it works for me without entering the Package/Receiver Class information.

**Comment by mathisdt** [comment]
I think without package and receiver class information the intent will be sent to all apps, not only to TWT. This is not necessary because other apps can't interpret it sensibly, but it doesn't do much harm either - maybe the battery will suffer a bit because all apps have to be woken up to receive the intent, but that should be neglectable.

**Comment by iceaway** [comment]
Thanks for the information, I was not aware of that. I'll add that too, I really do not want to increase the battery usage more than necessary :-)

**Comment by iceaway** [comment]
I just tried clocking in with a specific task, and it worked great, thanks!
