### ISSUE TITLE
"Count down to 0:00 every day" disabled does not work when day starts with positive flexitime

### ISSUE THREAD

**Issue by cultpony** [mathisdt/trackworktime#180]
Hi,

I'm using the app to keep track of my work hours, however I noticed that regardless of if I enable or disable "Count down to 0:00 every day", the app just shows me "regular work time is over since X:YY". This always happens when I end a day with more than 8 hours of flexitime left (ie, 11 hours of overtime) so the next day already starts with a positive flexitime.

The behaviour I would expect from this feature is that it ignores any amount of flexitime for every day except friday but it's taking flexitime into account every day.

**Comment by mathisdt** [comment]
Hi,
maybe I can shed some light on this. The option "use flexi time 0:00 as target" generally makes the notification take the flexi time into account. With this disabled, the daily work time simply is the weekly work time divided by the number of working days, e.g. 40 hours / 5 days = 8 daily hours.

When "use flexi time 0:00 as target" is enabled and "countdown to 0:00 every day" is disabled, the daily work time is the weekly work time divided by the number of working days. **Only** on the last working day of the week, the flexi time is taken into account. This seems to be your use case.

When "use flexi time 0:00 as target" is enabled and "countdown to 0:00 every day" is also enabled, the daily work time is the weekly work time divided by the number of working days, but **always** reduced by the overtime (or incremented by the undertime). So if the week starts with 11 hours overtime and you work 8 hours each day, the notification would always display "regular work time is over".

Maybe there's a "lag" in applying the options - if changes in the settings seem to make no difference, please try to clock out and in again (you can delete the extra events later). This way, the notification is recreated.

**Comment by cultpony** [comment]
I've recreated the notification over my lunchbreak, with "use flexi time 0:00" enabled and "countdown to 0:00 every day" disabled. It shows me "regular work time over since 6:xx" (daily target 8 hours, 40 hours weekly), the option seems to have simply no effect on what is displayed for me.

**Comment by mathisdt** [comment]
OK, I'll have a deeper look into it. I can't promise that it will be soon, I only do this on my free time alongside my full-time work and my family.

Thanks for raising the issue!

**Comment by mathisdt** [comment]
@cultpony I tested the situation you described in the current development version of TWT, and it seems to work as expected. Let me give you some details.

- Setup: I have a weekly target, I chose 5 hours so it's easier to calculate. I also have some overtime (way more than my daily working time of one hour). I enabled the notification and clocked in. 
- The first screenshot shows that my current flexi time is 24 hours and 34 minutes. The second screenshot tells me that my daily working time is over since 24 hours and 34 minutes - this is exactly the amount of time I have on top of my obligatory working time (which is the definition of "flexi time"). So far I can't find an error here, could you tell me where this is wrong? Or did I test something different than the situation you encountered?
- Maybe the irritation comes from the interpretation of the notification - the last bit is **hours and minutes**, not a time! If you interpret it as a point in time (you mentioned "6:xx" in your post above), then it doesn't make sense.

Screenshot 1 - App:
![Screenshot 1 - App](https://user-images.githubusercontent.com/1932462/136619403-be834d17-7b6a-4c3a-a7fa-4ec71dab62df.png)

Screenshot 2 - Notification:
![Screenshot 2 - Notification](https://user-images.githubusercontent.com/1932462/136619417-9ac1ea20-1e97-4629-985c-d62f28d538e7.png)

**Comment by mathisdt** [comment]
@cultpony Is your problem solved with this explanation?

**Comment by cultpony** [comment]
Hi, sorry for the delayed response, this got burried in my email inbox a bit.

My issue is that what you described earlier here;

> When "use flexi time 0:00 as target" is enabled and "countdown to 0:00 every day" is disabled, the daily work time is the weekly work time divided by the number of working days. Only on the last working day of the week, the flexi time is taken into account. This seems to be your use case.

, doesn't seem to be working. With "Use Flex Time 0:00 as target" enabled and "Countdown to 0:00 every day" disabled, the notification tells me that working time has been over for X:XX hours today, on Thursday. With the descriptions you've given I would expect it to instead tell me "Possible Finish Time HH:MM", but it only shows me that when I disable "Use Flex Time 0:00 as target" entirely.

On Friday, I would of course expect it to tell me work time is already over. Though with "Countdown to 0:00 every day" would expect that to be only the case on a friday, not for every day of the week.

The two below screenshots I've taken only toggling "Use Flex Time 0:00 as target", leaving "Countdown to 0:00 every day" **disabled** in both cases. The Flexi Time Target is 40 hours per week and my flexi time budget is currently at ~8 hours. It's definitely taking Flex Time into account even when it shouldn't, if I understand your comments so far right.

![pic1](https://user-images.githubusercontent.com/67918945/143470259-c074f352-5632-4539-b5ba-060f3f4f4fa8.jpg)
![pic2](https://user-images.githubusercontent.com/67918945/143470261-d1dbd32e-b78c-4342-9f23-c4850bfe5ca9.jpg)

**Comment by mathisdt** [comment]
Now I think I understand. It could be that the calculation for the notification was not considered when doing a major overhaul of the main calculation logic about half a year ago. I will investigate further.

**Comment by mathisdt** [comment]
You were right, there was a logic problem: the value for the option "count down to 0:00 every day" was always interpreted as being true, even if it was disabled. This is fixed for version 1.1.10 which will be released shortly.
