### ISSUE TITLE
[Feature Request] Calculate Salary

### ISSUE THREAD

**Issue by J0hnmey** [mathisdt/trackworktime#226]
Hello,
I would like to get within the app, be it in another tab or in the main screen, a calculation of my salary based on a preset value and the selected task and period. It would also be at cool if in the reports, the salary could be displayed in detail for the specific task, and also per day and week.  If this is possible, I would be happy to see it implemented.

I would also like to thank you for the great app

[Edit: typo]

**Comment by DamageIncorporated** [comment]
I sure would like such a feature, but this could get infinitely complex if you really want a rel7able result. 

I'll take my job as newspaper delivery man in germany an example:

I am assuming TWT calculates the salary pre-tax and insurance.  That is not even the value i'm interested in as a non-self-employed person.

I get a base salary per hour.
Additionally there's a premium for night times until 5:00. this is expressed as percentage of the base salary. I work on saturdays that get compensated whith another premium. 

Sometimes the newspaper is delivered on a sunday, because there is a holiday shortly before or after: You guessed it. I'm due for a different bonus. 

And finally: 3-4 four times a year, the newspaper is published on a holiday, which gives me the highest possible bonus.

I think this is a task for another App which could use TWT intends to calculate salaries based on rules and holiday calendar. Oh.. I forgot: Besides federal holidays,  the12 member states of the federal republic each add some extra holidays to the mix

**Comment by J0hnmey** [comment]
I actually just meant that you might be able to enter one or two fixed values on the basis of which the salary is then calculated. E.g. one value for normal working hours and one for overtime or weekends. For me, the calculation purely with the preset value is enough, so without taxes and insurance. Everything else, i.e. the calculation of the salary with taxes and insurance, as well as surcharges for vacations or the like, would really go beyond the scope.
