### ISSUE TITLE
Automatic Pause is unreliable

### ISSUE THREAD

**Issue by Bobbsterman** [mathisdt/trackworktime#241]
The Automatic Pause feature worked for the first few days and now doesn't seem to work: when I review the events for the day, I see it has not clocked me in and then out at the times I set for Automatic Pauses.

TWT v1.1.20
Android 13
Sony XQ-BQ72

P.S. This app was just what I was looking for, and I really appreciate your work!!

**Comment by mathisdt** [comment]
Hi, the Auto-Pause feature works like this: 
When the user clocks out (or generates a clock-out event via one of the automatisms), the app checks if the Auto-Pause should be applied. This is the case if:

- the user was already clocked in **before** the planned begin of the Auto-Pause _AND_
- the currently generated clock-out event is **after** the planned end of the Auto-Pause _AND_
- there were no other events **inside** the Auto-Pause time slot.

Of course it also doesn't work if the configured end is before the begin, but that doesn't seem to be the problem because it worked at first.

Please check if the above conditions are met in your case. Especially note that the Auto-Pause is not inserted **at the configured time** but later, when a clock-out happens after the configured pause. If the conditions are met and it still doesn't work, please [send me your log file](https://zephyrsoft.org/trackworktime/faq/#send-logs). I'll have a look at it and try to figure out what's happening.

**Comment by Bobbsterman** [comment]
Aaaah I see! Thanks for the details. I will test further – I probably just had the wrong expectations (but thinking harder, your design makes sense).

**Comment by Bobbsterman** [comment]
Yep, working totally as expected. Thanks! Closed :)
