### ISSUE TITLE
automatic Pause not working

### ISSUE THREAD

**Issue by carnager** [mathisdt/trackworktime#269]
When I set a start the end time for break and enable Auto Pause, nothing changes. I expect the app to stop counting in the configured time frame, but that does not happen

![Screenshot_20231211-131658_1](https://github.com/mathisdt/trackworktime/assets/3321178/7c1778ff-a6ad-44d2-8225-77e4530c953f)
![Screenshot_20231211-131719](https://github.com/mathisdt/trackworktime/assets/3321178/aee029fb-8114-49ba-8155-35cd620ed0ba)

**Comment by mathisdt** [comment]
Here's [a FAQ entry](https://zephyrsoft.org/trackworktime/faq/#what-does-the-%e2%80%9cautomatic-pause%e2%80%9d-do) for it. If that doesn't explain it enough, please reopen the issue and propose a better text - I'm happy to get help! :smiley:

**Comment by mathisdt** [comment]
BTW: There is the possibility to create events in an automated way, regardless of the inner workings of TWT. LlamaLab Automate or Tasker can do that just fine, please have a look at the description (including screenshots) on https://zephyrsoft.org/trackworktime/.

**Comment by carnager** [comment]
I tried to use automate... The screenshot shows an action called `org.zephyrsoft.trackworktime.ClockIn`
But I only get general android actions. and putting the action name manually gives an error

![Screenshot_20231211-190031](https://github.com/mathisdt/trackworktime/assets/3321178/2149872c-799b-4518-91f9-af244c4fe423)

**Comment by mathisdt** [comment]
It seems the Automate app was changed since I took the screenshots. I updated the important part for you in the description - you now have to switch on the "formula" mode and put the action in double quotes (see below).

If there are more questions, please email me directly (see https://zephyrsoft.org/contact-about-me/). Let's not use this issue as discussion forum.

![automate-4](https://github.com/mathisdt/trackworktime/assets/1932462/37ce31e2-c5be-4592-9ff7-406a643e2b2a)
