### ISSUE TITLE
Exporting Current Reports causes App to Crash

### ISSUE THREAD

**Issue by WreckingBANG** [mathisdt/trackworktime#298]
**Describe the bug**
When i try to export the Current Report of Week, Month or Year the App Crashes

**To Reproduce**
1. Go to Reports
2. Click on Current
3. Click on Export

**Expected behavior**
The App should not crash and just export the Current Export.

**Smartphone:**
 - Device: Pixel 7 Pro
 - OS: Android 13 (GrapheneOS, No GPlay)
 - Version: 1.1.24

**Additional context**
Logs are attached.
[Track Work Time log 082f5baef4d9.txt](https://github.com/user-attachments/files/16629762/Track.Work.Time.log.082f5baef4d9.txt)

**Comment by mathisdt** [comment]
Thanks for the elaborate bug report! With it, fixing the problem was easy. It came in via a PR which I didn't check thoroughly enough - my bad, but now it's fixed. However, I'm not sure when the next release will be, so it may take a while for the fix to hit Github / F-Droid / Google Play / Amazon...

**Comment by mathisdt** [comment]
To correct myself: I just created a release. You already can use it from Github if you initially installed from there, F-Droid usually will take some time to pick it up.

**Comment by WreckingBANG** [comment]
Works perfect, Thank you for the quick fix!
