### ISSUE TITLE
Notification permanently shown

### ISSUE THREAD

**Issue by musiKk** [mathisdt/trackworktime#41]
I just updated to 1.0.3 and now I have a notification that is permanently shown and cannot be removed. It says "automatic clock-in by location and/or WiFi active". Regardless of whether I check the notification setting or not the notification does not go away. I believe the notification should not be shown if the setting is not checked.

**Comment by mathisdt** [comment]
The notification came in with the fix for #37 because Android 8+ doesn't allow apps which are not visible to use background services (which TWT needs - if configured so - for checking the location and available WiFi networks). 

You can hide the notification if you don't want to see it: swipe it to the right, hold it there shortly and then use the cog icon to disable the notification channel "Track Work Time **Service** Notifications". Afterwards the permanent notification won't be shown anymore.

If you also switch off the notification channel "Track Work Time Notifications" then also the standard notifications will be hidden (discouraged, can be configured in more detail in the app's own settings).

**Comment by musiKk** [comment]
Thanks for your reply. This is super confusing. I just disabled the notification as you proposed. Out of curiosity I enabled it again but the notification did not come back. Weird.
