### ISSUE TITLE
Wifi tracking not working with Android Pie

### ISSUE THREAD

**Issue by musiKk** [mathisdt/trackworktime#55]
I recently upgraded my Samsung Galaxy S8 to Android Pie (9). Before that, Wifi tracking was working fine but now it just stopped. No events are logged at all. I already disabled battery optimization in the app's system settings (App Info - Optimize battery usage: Not optimized). Do you have some recommendation what could be done to enable this feature with the new Android version? Would be happy to provide you with more details.

**Comment by mathisdt** [comment]
@WildOrangutan devised a new method of tracking via wifi which is now well-tested and was released in version 1.0.5 today. Could you please check if that fixes your problem? 
If not, could you please provoke the situation by using TWT in reach of the configured wifi network (please open the app so the background issue won't be the problem - if it was at all). Afterwards please send me the logs (anonymized if you like), there's a menu item for that. I will see what I can do - but no promises!

**Comment by WildOrangutan** [comment]
I've pretty much fixed event "interruptions" and made sure wifi scan is always requested. Before that, app relied on other app's to trigger wifi scanning. So I guess it's possible this fixes your problem.

Another bug, that should be still present, is that wifi state is sometimes not correctly restored. So if you're for example clocked in with wifi and then force stop app, tracking won't work after that, since it still thinks it's clocked in. In that case, I think manual clock-in and clock-out fixes that. Something along those lines, it's been a while since I've messed around with it.

**Comment by musiKk** [comment]
I installed the update but did not respond last week because I was manually tracking time and I guess this messed with automated clock-in/-out. However I just arrived at work and got clocked in. So it seems it's back to working. If I find anything else, I'll let you know. Thanks for the app and your support!
